#!/bin/sh
set -e

if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
    systemctl stop    companion-web-dashboard.service >/dev/null 2>&1 || true
    systemctl disable companion-web-dashboard.service >/dev/null 2>&1 || true
fi

exit 0
